export interface LessonPhrase {
  id: string;
  text: string;
  romanization?: string;
  translation: string;
  hint?: string;
}

export interface Lesson {
  id: string;
  title: string;
  description: string;
  languageId: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  xpReward: number;
  duration: number;
  phrases: LessonPhrase[];
}

export const lessons: Lesson[] = [
  // ── ENGLISH ──────────────────────────────────────────────────────────────
  {
    id: "en-greetings",
    title: "Basic Greetings",
    description: "Essential greetings and introductions",
    languageId: "english",
    difficulty: "beginner",
    xpReward: 50,
    duration: 5,
    phrases: [
      { id: "1", text: "Hello, how are you?", translation: "General greeting", hint: "Stress 'how'" },
      { id: "2", text: "Good morning!", translation: "Morning greeting", hint: "Bright, upward tone" },
      { id: "3", text: "Good afternoon.", translation: "Afternoon greeting", hint: "Calm, level tone" },
      { id: "4", text: "Good evening!", translation: "Evening greeting", hint: "Softer than morning" },
      { id: "5", text: "Nice to meet you.", translation: "Meeting someone new", hint: "Link 'Nice' and 'to'" },
      { id: "6", text: "My name is...", translation: "Introducing yourself", hint: "Pause before your name" },
      { id: "7", text: "Have a great day!", translation: "Farewell phrase", hint: "Upward tone on 'day'" },
      { id: "8", text: "See you later!", translation: "Casual goodbye", hint: "Stress 'later'" },
      { id: "9", text: "Take care!", translation: "Warm farewell", hint: "Gentle, warm tone" },
      { id: "10", text: "How is everything going?", translation: "Asking how things are", hint: "Stress 'everything'" },
    ],
  },
  {
    id: "en-weather",
    title: "Talking About Weather",
    description: "Discuss weather conditions naturally",
    languageId: "english",
    difficulty: "beginner",
    xpReward: 60,
    duration: 7,
    phrases: [
      { id: "1", text: "The weather is beautiful today.", translation: "Describing nice weather", hint: "Stress 'beautiful'" },
      { id: "2", text: "It looks like rain.", translation: "Predicting rain", hint: "Draw out 'looks'" },
      { id: "3", text: "It is quite cold outside.", translation: "Describing cold weather", hint: "Emphasize 'cold'" },
      { id: "4", text: "The sun is shining brightly.", translation: "Sunny weather", hint: "Lift tone on 'brightly'" },
      { id: "5", text: "It is very hot today.", translation: "Describing heat", hint: "Stress 'very hot'" },
      { id: "6", text: "There is a strong wind.", translation: "Windy weather", hint: "Stress 'strong'" },
      { id: "7", text: "It is snowing heavily.", translation: "Heavy snowfall", hint: "Stress 'heavily'" },
      { id: "8", text: "What a lovely day!", translation: "Exclaiming about weather", hint: "Exclamatory tone" },
    ],
  },

  // ── SPANISH ───────────────────────────────────────────────────────────────
  {
    id: "es-greetings",
    title: "Saludos Básicos",
    description: "Basic Spanish greetings",
    languageId: "spanish",
    difficulty: "beginner",
    xpReward: 50,
    duration: 5,
    phrases: [
      { id: "1", text: "Hola, ¿cómo estás?", translation: "Hello, how are you?", hint: "Roll the 'r' lightly" },
      { id: "2", text: "Buenos días.", translation: "Good morning", hint: "Stress 'DÍ-as'" },
      { id: "3", text: "Buenas tardes.", translation: "Good afternoon", hint: "Soft 'd' sound" },
      { id: "4", text: "Buenas noches.", translation: "Good evening / Good night", hint: "Stress 'NO-ches'" },
      { id: "5", text: "Mucho gusto.", translation: "Nice to meet you", hint: "Short 'u' sounds" },
      { id: "6", text: "Me llamo...", translation: "My name is...", hint: "Double 'l' sounds like 'y'" },
      { id: "7", text: "¿De dónde eres?", translation: "Where are you from?", hint: "Accent on 'DÓN-de'" },
      { id: "8", text: "Hasta luego.", translation: "See you later", hint: "Soft 'g' in 'luego'" },
      { id: "9", text: "Por favor.", translation: "Please", hint: "Soften the 'v'" },
      { id: "10", text: "Gracias.", translation: "Thank you", hint: "Stress 'GRA-cias'" },
    ],
  },
  {
    id: "es-restaurant",
    title: "En el Restaurante",
    description: "Order food and drinks in Spanish",
    languageId: "spanish",
    difficulty: "intermediate",
    xpReward: 80,
    duration: 10,
    phrases: [
      { id: "1", text: "Una mesa para dos, por favor.", translation: "A table for two, please", hint: "Soften the 'v' in 'favor'" },
      { id: "2", text: "Me gustaría ordenar.", translation: "I would like to order", hint: "Roll the 'r' in 'ordenar'" },
      { id: "3", text: "La cuenta, por favor.", translation: "The check, please", hint: "Stress 'CUEN-ta'" },
      { id: "4", text: "¿Qué recomienda usted?", translation: "What do you recommend?", hint: "Stress 're-co-MIEN-da'" },
      { id: "5", text: "Quisiera un café con leche.", translation: "I would like a coffee with milk", hint: "Stress 'ca-FÉ'" },
      { id: "6", text: "¿Tiene opciones vegetarianas?", translation: "Do you have vegetarian options?", hint: "Stress 've-ge-ta-RIA-nas'" },
      { id: "7", text: "Está delicioso.", translation: "It is delicious", hint: "Stress 'de-li-CIO-so'" },
      { id: "8", text: "¿Puedo pagar con tarjeta?", translation: "Can I pay by card?", hint: "Roll the 'r' in 'tarjeta'" },
    ],
  },

  // ── FRENCH ────────────────────────────────────────────────────────────────
  {
    id: "fr-greetings",
    title: "Salutations de Base",
    description: "Essential French greetings",
    languageId: "french",
    difficulty: "beginner",
    xpReward: 50,
    duration: 5,
    phrases: [
      { id: "1", text: "Bonjour, comment allez-vous?", translation: "Hello, how are you? (formal)", hint: "Silent 's' at end" },
      { id: "2", text: "Bonsoir.", translation: "Good evening", hint: "Nasal 'on' sound" },
      { id: "3", text: "Enchanté de vous rencontrer.", translation: "Nice to meet you", hint: "Nasal 'en' sounds" },
      { id: "4", text: "Je m'appelle...", translation: "My name is...", hint: "Liaison between words" },
      { id: "5", text: "Bonne journée!", translation: "Have a nice day!", hint: "Stress 'jour-NÉE'" },
      { id: "6", text: "Au revoir.", translation: "Goodbye", hint: "Stress 're-VOIR'" },
      { id: "7", text: "S'il vous plaît.", translation: "Please (formal)", hint: "Liaison between words" },
      { id: "8", text: "Merci beaucoup.", translation: "Thank you very much", hint: "Silent 'p' in 'beaucoup'" },
      { id: "9", text: "Comment vous appelez-vous?", translation: "What is your name? (formal)", hint: "Liaison 'vous-ap'" },
      { id: "10", text: "D'où venez-vous?", translation: "Where are you from?", hint: "Stress 've-NEZ'" },
    ],
  },
  {
    id: "fr-daily",
    title: "La Vie Quotidienne",
    description: "Everyday French expressions",
    languageId: "french",
    difficulty: "intermediate",
    xpReward: 70,
    duration: 8,
    phrases: [
      { id: "1", text: "Je voudrais un café, s'il vous plaît.", translation: "I would like a coffee, please", hint: "Stress 'vou-DRAIS'" },
      { id: "2", text: "Où est la gare?", translation: "Where is the train station?", hint: "Short 'où' sound" },
      { id: "3", text: "Combien ça coûte?", translation: "How much does it cost?", hint: "Nasal 'ien'" },
      { id: "4", text: "Je ne comprends pas.", translation: "I don't understand", hint: "Nasal 'en' in 'comprends'" },
      { id: "5", text: "Pouvez-vous répéter, s'il vous plaît?", translation: "Can you repeat, please?", hint: "Stress 'ré-PÉ-ter'" },
      { id: "6", text: "Le temps est magnifique.", translation: "The weather is magnificent", hint: "Nasal 'em' in 'temps'" },
      { id: "7", text: "J'habite à Paris.", translation: "I live in Paris", hint: "Silent 'h' in 'habite'" },
      { id: "8", text: "Bonne nuit.", translation: "Good night", hint: "Stress 'NUIT'" },
    ],
  },

  // ── GERMAN ────────────────────────────────────────────────────────────────
  {
    id: "de-greetings",
    title: "Grundlegende Begrüßung",
    description: "Basic German greetings",
    languageId: "german",
    difficulty: "beginner",
    xpReward: 50,
    duration: 5,
    phrases: [
      { id: "1", text: "Guten Tag, wie geht es Ihnen?", translation: "Good day, how are you? (formal)", hint: "Pronounce 'ch' in throat" },
      { id: "2", text: "Guten Morgen.", translation: "Good morning", hint: "Stress 'MOR-gen'" },
      { id: "3", text: "Guten Abend.", translation: "Good evening", hint: "Stress 'A-bend'" },
      { id: "4", text: "Freut mich, Sie kennenzulernen.", translation: "Nice to meet you", hint: "Clear 'eu' sound" },
      { id: "5", text: "Ich heiße...", translation: "My name is...", hint: "Soft 'ss' sound in 'heiße'" },
      { id: "6", text: "Auf Wiedersehen.", translation: "Goodbye (formal)", hint: "Stress 'WIE-der-se-hen'" },
      { id: "7", text: "Tschüss!", translation: "Bye! (informal)", hint: "Similar to English 'choose'" },
      { id: "8", text: "Bitte.", translation: "Please / You're welcome", hint: "Short 'i' sound" },
      { id: "9", text: "Danke schön.", translation: "Thank you very much", hint: "Stress 'SCHÖN'" },
      { id: "10", text: "Woher kommen Sie?", translation: "Where are you from?", hint: "Stress 'KOM-men'" },
    ],
  },
  {
    id: "de-daily",
    title: "Alltägliche Ausdrücke",
    description: "Everyday German expressions",
    languageId: "german",
    difficulty: "intermediate",
    xpReward: 70,
    duration: 8,
    phrases: [
      { id: "1", text: "Ich möchte einen Kaffee, bitte.", translation: "I would like a coffee, please", hint: "Umlaut 'ö' like in 'sir'" },
      { id: "2", text: "Wo ist der Bahnhof?", translation: "Where is the train station?", hint: "Stress 'BAHN-hof'" },
      { id: "3", text: "Was kostet das?", translation: "What does this cost?", hint: "Stress 'KOS-tet'" },
      { id: "4", text: "Ich verstehe nicht.", translation: "I don't understand", hint: "Stress 'ver-STE-he'" },
      { id: "5", text: "Können Sie das wiederholen?", translation: "Can you repeat that?", hint: "Stress 'wie-der-HO-len'" },
      { id: "6", text: "Das Wetter ist schön.", translation: "The weather is nice", hint: "Umlaut 'ö' in 'schön'" },
      { id: "7", text: "Ich wohne in Berlin.", translation: "I live in Berlin", hint: "Stress 'WOH-ne'" },
      { id: "8", text: "Gute Nacht.", translation: "Good night", hint: "Stress 'NACHT'" },
    ],
  },

  // ── JAPANESE ──────────────────────────────────────────────────────────────
  {
    id: "ja-greetings",
    title: "基本の挨拶",
    description: "Essential Japanese greetings",
    languageId: "japanese",
    difficulty: "beginner",
    xpReward: 60,
    duration: 6,
    phrases: [
      { id: "1", text: "おはようございます", romanization: "Ohayō gozaimasu", translation: "Good morning (formal)", hint: "Even stress on syllables" },
      { id: "2", text: "こんにちは", romanization: "Konnichiwa", translation: "Hello / Good afternoon", hint: "Flat intonation" },
      { id: "3", text: "こんばんは", romanization: "Konbanwa", translation: "Good evening", hint: "Stress 'ban'" },
      { id: "4", text: "はじめまして", romanization: "Hajimemashite", translation: "Nice to meet you", hint: "Slight pause after 'ha'" },
      { id: "5", text: "わたしのなまえは", romanization: "Watashi no namae wa", translation: "My name is...", hint: "Soft 'wa' particle at end" },
      { id: "6", text: "ありがとうございます", romanization: "Arigatō gozaimasu", translation: "Thank you very much", hint: "Stress 'go-zai-masu'" },
      { id: "7", text: "さようなら", romanization: "Sayōnara", translation: "Goodbye", hint: "Stress 'yō'" },
      { id: "8", text: "おやすみなさい", romanization: "Oyasumi nasai", translation: "Good night", hint: "Gentle falling tone" },
      { id: "9", text: "いただきます", romanization: "Itadakimasu", translation: "Let's eat (before meals)", hint: "Humble, respectful tone" },
      { id: "10", text: "すみません", romanization: "Sumimasen", translation: "Excuse me / Sorry", hint: "Stress 'mi'" },
    ],
  },
  {
    id: "ja-daily",
    title: "日常会話",
    description: "Everyday Japanese expressions",
    languageId: "japanese",
    difficulty: "intermediate",
    xpReward: 80,
    duration: 10,
    phrases: [
      { id: "1", text: "コーヒーをください", romanization: "Kōhī wo kudasai", translation: "Coffee, please", hint: "Long vowel in 'Kōhī'" },
      { id: "2", text: "えきはどこですか", romanization: "Eki wa doko desu ka", translation: "Where is the station?", hint: "Rising tone on 'ka'" },
      { id: "3", text: "いくらですか", romanization: "Ikura desu ka", translation: "How much is it?", hint: "Rising question tone" },
      { id: "4", text: "わかりません", romanization: "Wakarimasen", translation: "I don't understand", hint: "Stress 'wa-ka'" },
      { id: "5", text: "もう一度おねがいします", romanization: "Mō ichido onegaishimasu", translation: "Please say it again", hint: "Long 'ō' in 'mō'" },
      { id: "6", text: "トイレはどこですか", romanization: "Toire wa doko desu ka", translation: "Where is the restroom?", hint: "Rising question tone" },
      { id: "7", text: "おいしいです", romanization: "Oishii desu", translation: "It is delicious", hint: "Stress 'oi-SHI'" },
      { id: "8", text: "てつだってください", romanization: "Tetsudatte kudasai", translation: "Please help me", hint: "Polite request form" },
    ],
  },

  // ── CHINESE ───────────────────────────────────────────────────────────────
  {
    id: "zh-greetings",
    title: "基本问��",
    description: "Essential Mandarin Chinese greetings",
    languageId: "chinese",
    difficulty: "beginner",
    xpReward: 70,
    duration: 8,
    phrases: [
      { id: "1", text: "你好", romanization: "Nǐ hǎo", translation: "Hello", hint: "3rd tone on both: rise-fall" },
      { id: "2", text: "你好吗", romanization: "Nǐ hǎo ma", translation: "How are you?", hint: "Neutral 'ma' at end" },
      { id: "3", text: "早上好", romanization: "Zǎoshang hǎo", translation: "Good morning", hint: "3rd tone on 'zǎo'" },
      { id: "4", text: "晚上好", romanization: "Wǎnshang hǎo", translation: "Good evening", hint: "3rd tone on 'wǎn'" },
      { id: "5", text: "我叫", romanization: "Wǒ jiào", translation: "My name is...", hint: "Falling-rising tone on 'wǒ'" },
      { id: "6", text: "谢谢", romanization: "Xièxiè", translation: "Thank you", hint: "4th tone, falling sharply" },
      { id: "7", text: "不客气", romanization: "Bù kèqì", translation: "You're welcome", hint: "4th tone on 'bù'" },
      { id: "8", text: "再见", romanization: "Zàijiàn", translation: "Goodbye", hint: "4th tone on both" },
      { id: "9", text: "晚安", romanization: "Wǎn'ān", translation: "Good night", hint: "3rd then 1st tone" },
      { id: "10", text: "很高兴认识你", romanization: "Hěn gāoxìng rènshi nǐ", translation: "Nice to meet you", hint: "Stress 'gāo-XÌNG'" },
    ],
  },
  {
    id: "zh-daily",
    title: "日常用语",
    description: "Everyday Mandarin expressions",
    languageId: "chinese",
    difficulty: "intermediate",
    xpReward: 80,
    duration: 10,
    phrases: [
      { id: "1", text: "请给我一杯咖啡", romanization: "Qǐng gěi wǒ yī bēi kāfēi", translation: "Please give me a coffee", hint: "3rd tone on 'qǐng'" },
      { id: "2", text: "火车站在哪里", romanization: "Huǒchē zhàn zài nǎlǐ", translation: "Where is the train station?", hint: "Stress 'nǎ-lǐ'" },
      { id: "3", text: "这个多少钱", romanization: "Zhège duōshao qián", translation: "How much is this?", hint: "Stress 'duō-shao'" },
      { id: "4", text: "我听不懂", romanization: "Wǒ tīng bù dǒng", translation: "I don't understand", hint: "Stress 'bù dǒng'" },
      { id: "5", text: "请再说一遍", romanization: "Qǐng zài shuō yībiàn", translation: "Please say it again", hint: "4th tone on 'zài'" },
      { id: "6", text: "好吃", romanization: "Hǎo chī", translation: "Delicious", hint: "3rd then 1st tone" },
      { id: "7", text: "我住在北京", romanization: "Wǒ zhù zài Běijīng", translation: "I live in Beijing", hint: "3rd tone on 'wǒ' and 'běi'" },
      { id: "8", text: "帮帮我", romanization: "Bāng bāng wǒ", translation: "Please help me", hint: "1st tone on 'bāng'" },
    ],
  },

  // ── KOREAN ────────────────────────────────────────────────────────────────
  {
    id: "ko-greetings",
    title: "기본 인사",
    description: "Essential Korean greetings",
    languageId: "korean",
    difficulty: "beginner",
    xpReward: 60,
    duration: 6,
    phrases: [
      { id: "1", text: "안녕하세요", romanization: "Annyeonghaseyo", translation: "Hello (formal)", hint: "Stress 'ha-se-yo'" },
      { id: "2", text: "안녕히 가세요", romanization: "Annyeonghi gaseyo", translation: "Goodbye (to the one leaving)", hint: "Stress 'ga-se-yo'" },
      { id: "3", text: "감사합니다", romanization: "Gamsahamnida", translation: "Thank you (formal)", hint: "Stress 'ham-ni-da'" },
      { id: "4", text: "처음 뵙겠습니다", romanization: "Cheoeum boepgesseumnida", translation: "Nice to meet you", hint: "Formal, respectful tone" },
      { id: "5", text: "제 이름은", romanization: "Je ireumeun", translation: "My name is...", hint: "Soft 'j' sound" },
      { id: "6", text: "좋은 아침이에요", romanization: "Joeun achimieyo", translation: "Good morning", hint: "Stress 'a-chim'" },
      { id: "7", text: "좋은 저녁이에요", romanization: "Joeun jeonyeogieyo", translation: "Good evening", hint: "Stress 'jeo-nyeog'" },
      { id: "8", text: "잘 자요", romanization: "Jal jayo", translation: "Good night", hint: "Gentle, soft tone" },
      { id: "9", text: "반가워요", romanization: "Bangawoyo", translation: "Nice to meet you (casual)", hint: "Stress 'ban-ga'" },
      { id: "10", text: "어디서 오셨어요", romanization: "Eodiseo osyeosseoyo", translation: "Where are you from?", hint: "Rising question tone" },
    ],
  },
  {
    id: "ko-daily",
    title: "일상 표현",
    description: "Everyday Korean expressions",
    languageId: "korean",
    difficulty: "intermediate",
    xpReward: 80,
    duration: 10,
    phrases: [
      { id: "1", text: "커피 한 잔 주세요", romanization: "Keopi han jan juseyo", translation: "One coffee, please", hint: "Polite ending '-seyo'" },
      { id: "2", text: "역이 어디예요", romanization: "Yeogi eodiyeyo", translation: "Where is the station?", hint: "Rising question tone" },
      { id: "3", text: "이거 얼마예요", romanization: "Igeo eolmayeyo", translation: "How much is this?", hint: "Stress 'eol-ma'" },
      { id: "4", text: "이해가 안 돼요", romanization: "Ihaega an dwaeyo", translation: "I don't understand", hint: "Stress 'an dwaé-yo'" },
      { id: "5", text: "다시 한 번 말씀해 주세요", romanization: "Dasi han beon malsseum haejuseyo", translation: "Please say it again", hint: "Formal polite form" },
      { id: "6", text: "맛있어요", romanization: "Masisseoyo", translation: "It is delicious", hint: "Stress 'ma-sit'" },
      { id: "7", text: "저는 서울에 살아요", romanization: "Jeoneun Seoure sarayo", translation: "I live in Seoul", hint: "Stress 'sa-ra-yo'" },
      { id: "8", text: "도와주세요", romanization: "Dowajuseyo", translation: "Please help me", hint: "Polite request form" },
    ],
  },

  // ── PORTUGUESE ────────────────────────────────────────────────────────────
  {
    id: "pt-greetings",
    title: "Saudações Básicas",
    description: "Basic Portuguese greetings",
    languageId: "portuguese",
    difficulty: "beginner",
    xpReward: 50,
    duration: 5,
    phrases: [
      { id: "1", text: "Olá, como você está?", translation: "Hello, how are you?", hint: "Stress 'es-TÁ'" },
      { id: "2", text: "Bom dia.", translation: "Good morning", hint: "Nasal 'bom'" },
      { id: "3", text: "Boa tarde.", translation: "Good afternoon", hint: "Open 'boa'" },
      { id: "4", text: "Boa noite.", translation: "Good evening / Good night", hint: "Stress 'NOI-te'" },
      { id: "5", text: "Prazer em conhecê-lo.", translation: "Nice to meet you", hint: "Stress 'co-nhe-CÊ'" },
      { id: "6", text: "Meu nome é...", translation: "My name is...", hint: "Nasal 'nome'" },
      { id: "7", text: "Tchau!", translation: "Bye! (informal, Brazilian)", hint: "Like Italian 'ciao'" },
      { id: "8", text: "Por favor.", translation: "Please", hint: "Stress 'fa-VOR'" },
      { id: "9", text: "Obrigado / Obrigada.", translation: "Thank you (m/f)", hint: "Stress 'o-bri-GA-do'" },
      { id: "10", text: "De onde você é?", translation: "Where are you from?", hint: "Stress 'vo-CÊ'" },
    ],
  },
  {
    id: "pt-daily",
    title: "Expressões do Dia a Dia",
    description: "Everyday Portuguese expressions",
    languageId: "portuguese",
    difficulty: "intermediate",
    xpReward: 70,
    duration: 8,
    phrases: [
      { id: "1", text: "Gostaria de um café, por favor.", translation: "I would like a coffee, please", hint: "Stress 'ca-FÉ'" },
      { id: "2", text: "Onde fica a estação?", translation: "Where is the station?", hint: "Stress 'es-ta-ÇÃO'" },
      { id: "3", text: "Quanto custa isso?", translation: "How much does this cost?", hint: "Stress 'CUSTA'" },
      { id: "4", text: "Não entendo.", translation: "I don't understand", hint: "Nasal 'não'" },
      { id: "5", text: "Pode repetir, por favor?", translation: "Can you repeat, please?", hint: "Stress 're-pe-TIR'" },
      { id: "6", text: "Está delicioso.", translation: "It is delicious", hint: "Stress 'de-li-CIO-so'" },
      { id: "7", text: "Eu moro em Lisboa.", translation: "I live in Lisbon", hint: "Stress 'Lis-BOA'" },
      { id: "8", text: "Boa noite, durma bem.", translation: "Good night, sleep well", hint: "Stress 'DUR-ma bem'" },
    ],
  },

  // ── ITALIAN ───────────────────────────────────────────────────────────────
  {
    id: "it-greetings",
    title: "Saluti di Base",
    description: "Basic Italian greetings",
    languageId: "italian",
    difficulty: "beginner",
    xpReward: 50,
    duration: 5,
    phrases: [
      { id: "1", text: "Ciao, come stai?", translation: "Hi, how are you? (informal)", hint: "'Ciao' like 'chow'" },
      { id: "2", text: "Buongiorno.", translation: "Good morning / Good day", hint: "Stress 'buo-NGIOR-no'" },
      { id: "3", text: "Buonasera.", translation: "Good evening", hint: "Stress 'se-RA'" },
      { id: "4", text: "Buonanotte.", translation: "Good night", hint: "Stress 'NOT-te'" },
      { id: "5", text: "Piacere di conoscerti.", translation: "Nice to meet you (informal)", hint: "Stress 'co-NOS-cer-ti'" },
      { id: "6", text: "Mi chiamo...", translation: "My name is...", hint: "Stress 'CHIA-mo'" },
      { id: "7", text: "Arrivederci.", translation: "Goodbye (formal)", hint: "Stress 'a-rri-ve-DER-ci'" },
      { id: "8", text: "Per favore.", translation: "Please", hint: "Stress 'fa-VO-re'" },
      { id: "9", text: "Grazie mille.", translation: "Thank you very much", hint: "Stress 'GRA-zie MIL-le'" },
      { id: "10", text: "Di dove sei?", translation: "Where are you from?", hint: "Stress 'DO-ve sei'" },
    ],
  },
  {
    id: "it-daily",
    title: "Espressioni Quotidiane",
    description: "Everyday Italian expressions",
    languageId: "italian",
    difficulty: "intermediate",
    xpReward: 70,
    duration: 8,
    phrases: [
      { id: "1", text: "Vorrei un caffè, per favore.", translation: "I would like a coffee, please", hint: "Stress 'caf-FÈ'" },
      { id: "2", text: "Dov'è la stazione?", translation: "Where is the station?", hint: "Stress 'sta-ZIO-ne'" },
      { id: "3", text: "Quanto costa?", translation: "How much does it cost?", hint: "Stress 'CO-sta'" },
      { id: "4", text: "Non capisco.", translation: "I don't understand", hint: "Stress 'ca-PI-sco'" },
      { id: "5", text: "Può ripetere, per favore?", translation: "Can you repeat, please?", hint: "Stress 'ri-pe-TE-re'" },
      { id: "6", text: "È buonissimo.", translation: "It is very good", hint: "Stress 'buo-NIS-si-mo'" },
      { id: "7", text: "Abito a Roma.", translation: "I live in Rome", hint: "Stress 'A-bi-to'" },
      { id: "8", text: "Aiuto, per favore!", translation: "Help, please!", hint: "Stress 'a-IU-to'" },
    ],
  },

  // ── ARABIC ────────────────────────────────────────────────────────────────
  {
    id: "ar-greetings",
    title: "التحيات الأساسية",
    description: "Essential Arabic greetings",
    languageId: "arabic",
    difficulty: "beginner",
    xpReward: 70,
    duration: 8,
    phrases: [
      { id: "1", text: "مرحبا", romanization: "Marhaba", translation: "Hello", hint: "Stress 'MAR-ha-ba'" },
      { id: "2", text: "السلام عليكم", romanization: "As-salāmu ʿalaykum", translation: "Peace be upon you (greeting)", hint: "Stress 'a-LAY-kum'" },
      { id: "3", text: "صباح الخير", romanization: "Ṣabāḥ al-khayr", translation: "Good morning", hint: "Guttural 'kh' sound" },
      { id: "4", text: "مساء الخير", romanization: "Masāʾ al-khayr", translation: "Good evening", hint: "Long 'ā' in 'masāʾ'" },
      { id: "5", text: "تشرفنا", romanization: "Tasharrafnā", translation: "Nice to meet you", hint: "Stress 'SHAR-raf'" },
      { id: "6", text: "اسمي", romanization: "Ismi", translation: "My name is...", hint: "Short 'is-mi'" },
      { id: "7", text: "شكراً جزيلاً", romanization: "Shukran jazīlan", translation: "Thank you very much", hint: "Stress 'ja-ZĪ-lan'" },
      { id: "8", text: "مع السلامة", romanization: "Maʿa as-salāma", translation: "Goodbye", hint: "Stress 'sa-LĀ-ma'" },
      { id: "9", text: "تصبح على خير", romanization: "Tuṣbiḥ ʿalā khayr", translation: "Good night", hint: "Said to the one going to sleep" },
      { id: "10", text: "من أين أنت؟", romanization: "Min ayna anta?", translation: "Where are you from?", hint: "Stress 'AY-na'" },
    ],
  },
  {
    id: "ar-daily",
    title: "التعبيرات اليومية",
    description: "Everyday Arabic expressions",
    languageId: "arabic",
    difficulty: "intermediate",
    xpReward: 80,
    duration: 10,
    phrases: [
      { id: "1", text: "أريد قهوة من فضلك", romanization: "Urīdu qahwatan min faḍlika", translation: "I want a coffee, please", hint: "Stress 'QAH-wa'" },
      { id: "2", text: "أين محطة القطار؟", romanization: "Ayna maḥaṭṭat al-qiṭār?", translation: "Where is the train station?", hint: "Stress 'ma-ḤAṬ-ṭa'" },
      { id: "3", text: "كم ثمن هذا؟", romanization: "Kam thaman hādhā?", translation: "How much does this cost?", hint: "Stress 'THA-man'" },
      { id: "4", text: "لا أفهم", romanization: "Lā afham", translation: "I don't understand", hint: "Long 'lā'" },
      { id: "5", text: "هل يمكنك التكرار؟", romanization: "Hal yumkinuka at-tikrār?", translation: "Can you repeat?", hint: "Stress 'at-ti-KRĀ R'" },
      { id: "6", text: "هذا لذيذ", romanization: "Hādhā ladhīdh", translation: "This is delicious", hint: "Long 'ī' in 'ladhīdh'" },
      { id: "7", text: "أسكن في القاهرة", romanization: "Askunu fī al-Qāhira", translation: "I live in Cairo", hint: "Stress 'QĀ-hi-ra'" },
      { id: "8", text: "ساعدني من فضلك", romanization: "Sāʿidnī min faḍlika", translation: "Help me, please", hint: "Stress 'SĀ-ʿid'" },
    ],
  },
  // ── TAGALOG ──────────────────────────────────────────────────────
  {
    id: "tl-greetings",
    title: "Mga Pagbati",
    description: "Basic Tagalog greetings and introductions",
    languageId: "tagalog",
    difficulty: "beginner",
    xpReward: 50,
    duration: 5,
    phrases: [
      { id: "1",  text: "Magandang umaga!", translation: "Good morning!", hint: "Stress 'ma-GAN-dang'" },
      { id: "2",  text: "Kumusta ka?", translation: "How are you?", hint: "Stress 'ku-MUS-ta'" },
      { id: "3",  text: "Mabuti naman, salamat.", translation: "I'm fine, thank you.", hint: "Stress 'sa-LA-mat'" },
      { id: "4",  text: "Ako si...", translation: "I am... (introducing yourself)", hint: "Pause before your name" },
      { id: "5",  text: "Natutuwa akong makilala ka.", translation: "Nice to meet you.", hint: "Stress 'na-tu-TU-wa'" },
      { id: "6",  text: "Paalam.", translation: "Goodbye.", hint: "Stress 'pa-A-lam'" },
      { id: "7",  text: "Salamat!", translation: "Thank you!", hint: "Warm, upbeat tone" },
      { id: "8",  text: "Walang anuman.", translation: "You're welcome.", hint: "Stress 'wa-LANG'" },
      { id: "9",  text: "Magandang hapon!", translation: "Good afternoon!", hint: "Stress 'ha-PON'" },
      { id: "10", text: "Magandang gabi!", translation: "Good evening!", hint: "Stress 'ga-BI'" },
    ],
  },
  {
    id: "tl-daily",
    title: "Pang-araw-araw na Parirala",
    description: "Everyday Tagalog expressions",
    languageId: "tagalog",
    difficulty: "intermediate",
    xpReward: 65,
    duration: 8,
    phrases: [
      { id: "1", text: "Saan ka pupunta?", translation: "Where are you going?", hint: "Stress 'pu-PUN-ta'" },
      { id: "2", text: "Gusto ko ng kape.", translation: "I want coffee.", hint: "Stress 'KA-pe'" },
      { id: "3", text: "Magkano ito?", translation: "How much is this?", hint: "Stress 'mag-KA-no'" },
      { id: "4", text: "Hindi ko maintindihan.", translation: "I don't understand.", hint: "Stress 'ma-in-TIN-di-han'" },
      { id: "5", text: "Pwede mo bang ulitin?", translation: "Can you repeat that?", hint: "Stress 'u-LI-tin'" },
      { id: "6", text: "Masarap ang pagkain!", translation: "The food is delicious!", hint: "Stress 'ma-sa-RAP'" },
      { id: "7", text: "Nakatira ako sa Maynila.", translation: "I live in Manila.", hint: "Stress 'May-NI-la'" },
      { id: "8", text: "Tulungan mo ako.", translation: "Help me please.", hint: "Stress 'tu-LUN-gan'" },
    ],
  },
  {
    id: "tl-travel",
    title: "Paglalakbay at Direksyon",
    description: "Travel phrases and directions in Tagalog",
    languageId: "tagalog",
    difficulty: "intermediate",
    xpReward: 70,
    duration: 9,
    phrases: [
      { id: "1", text: "Nasaan ang paliparan?", translation: "Where is the airport?", hint: "Stress 'pa-li-PA-ran'" },
      { id: "2", text: "Isang tiket papunta sa Cebu.", translation: "One ticket to Cebu.", hint: "Stress 'ti-KET'" },
      { id: "3", text: "Kumanan ka sa susunod na kanto.", translation: "Turn right at the next corner.", hint: "Stress 'ku-MA-nan'" },
      { id: "4", text: "Gaano kalayo ang hotel?", translation: "How far is the hotel?", hint: "Stress 'ga-A-no'" },
      { id: "5", text: "Magtatawid ako ng daan.", translation: "I will cross the street.", hint: "Stress 'mag-ta-TA-wid'" },
      { id: "6", text: "Huwag akong iwan.", translation: "Don't leave me behind.", hint: "Stress 'hu-WAG'" },
      { id: "7", text: "Malapit na ba tayo?", translation: "Are we almost there?", hint: "Stress 'ma-LA-pit'" },
      { id: "8", text: "Dito na kami bumaba.", translation: "We get off here.", hint: "Stress 'bu-MA-ba'" },
    ],
  },
];

export const getLessonsByLanguage = (languageId: string): Lesson[] =>
  lessons.filter((l) => l.languageId === languageId);

export const getLessonById = (lessonId: string): Lesson | undefined =>
  lessons.find((l) => l.id === lessonId);

export const getAllLessons = (): Lesson[] => lessons;
